FROM redocly/redoc

ENV REDOC_OPTIONS='\
  disable-search \
  expand-responses=false \
  schema-expansion-level=all \
  json-sample-expand-level=all \
  theme={"breakpoints":{"small":"60rem","medium":"90rem","large":"120rem"},"sidebar":{"width":"400px"}}'
